common:
  ckpt_path:
  seed: 1234
  
model_checkpoint:
  dirpath: C:/Users/GorbachPP/PycharmProjects/BertFT/checkpoints/exp_2
  filename: "{step}"
  monitor: 'train_loss'
  mode: "min"
  save_top_k: -1
  #every_n_train_steps: 10000
  every_n_epochs: 1
  
data:
  dataloader:
    batch_size: 400
    num_workers: 0
    
optimizer:
  params:
    lr: 0.00005
    weight_decay: 0.0
    betas: [0.9, 0.998]
    eps: 1e-5